apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    olm.skipRange: '>=4.13.0 <4.14.0'
  name: numaresources-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NUMAResourcesOperator is the Schema for the numaresourcesoperators
        API
      displayName: NUMA Resources Operator
      kind: NUMAResourcesOperator
      name: numaresourcesoperators.nodetopology.openshift.io
      resources:
      - kind: DaemonSet
        name: ""
        version: v1
      specDescriptors:
      - description: Optional Resource Topology Exporter image URL
        displayName: Optional RTE image URL
        path: imageSpec
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Valid values are: "Normal", "Debug", "Trace", "TraceAll". Defaults
          to "Normal".'
        displayName: RTE log verbosity
        path: logLevel
      - description: Group of Nodes to enable RTE on
        displayName: Group of nodes to enable RTE on
        path: nodeGroups
      - description: InfoRefreshMode sets the mechanism which will be used to refresh
          the topology info.
        displayName: Topology info mechanism setting
        path: nodeGroups[0].config.infoRefreshMode
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: InfoRefreshPeriod sets the topology info refresh period. Use
          explicit 0 to disable.
        displayName: Topology info refresh period setting
        path: nodeGroups[0].config.infoRefreshPeriod
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: PodsFingerprinting defines if pod fingerprint should be reported
          for the machines belonging to this group
        displayName: Enable or disable the pods fingerprinting setting
        path: nodeGroups[0].config.podsFingerprinting
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Optional Namespace/Name glob patterns of pod to ignore at node
          level
        displayName: Optional ignore pod namespace/name glob patterns
        path: podExcludes
      statusDescriptors:
      - description: Conditions show the current state of the NUMAResourcesOperator
          Operator
        displayName: Condition reported
        path: conditions
      - description: DaemonSets of the configured RTEs, one per node group
        displayName: RTE DaemonSets
        path: daemonsets
      - description: MachineConfigPools resolved from configured node groups
        displayName: RTE MCPs from node groups
        path: machineconfigpools
      - description: Conditions represents the latest available observations of MachineConfigPool
          current state.
        displayName: Optional conditions reported for this NodeGroup
        path: machineconfigpools[0].conditions
      - description: NodeGroupConfig represents the latest available configuration
          applied to this MachineConfigPool
        displayName: Optional configuration enforced on this NodeGroup
        path: machineconfigpools[0].config
      version: v1
    - description: NUMAResourcesOperator is the Schema for the numaresourcesoperators
        API
      displayName: NUMA Resources Operator
      kind: NUMAResourcesOperator
      name: numaresourcesoperators.nodetopology.openshift.io
      resources:
      - kind: DaemonSet
        name: ""
        version: v1
      specDescriptors:
      - description: Optional Resource Topology Exporter image URL
        displayName: Optional RTE image URL
        path: imageSpec
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Valid values are: "Normal", "Debug", "Trace", "TraceAll". Defaults
          to "Normal".'
        displayName: RTE log verbosity
        path: logLevel
      - description: Group of Nodes to enable RTE on
        displayName: Group of nodes to enable RTE on
        path: nodeGroups
      - description: InfoRefreshMode sets the mechanism which will be used to refresh
          the topology info.
        displayName: Topology info mechanism setting
        path: nodeGroups[0].config.infoRefreshMode
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: InfoRefreshPeriod sets the topology info refresh period. Use
          explicit 0 to disable.
        displayName: Topology info refresh period setting
        path: nodeGroups[0].config.infoRefreshPeriod
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: PodsFingerprinting defines if pod fingerprint should be reported
          for the machines belonging to this group
        displayName: Enable or disable the pods fingerprinting setting
        path: nodeGroups[0].config.podsFingerprinting
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Optional Namespace/Name glob patterns of pod to ignore at node
          level
        displayName: Optional ignore pod namespace/name glob patterns
        path: podExcludes
      statusDescriptors:
      - description: Conditions show the current state of the NUMAResourcesOperator
          Operator
        displayName: Condition reported
        path: conditions
      - description: DaemonSets of the configured RTEs, one per node group
        displayName: RTE DaemonSets
        path: daemonsets
      - description: MachineConfigPools resolved from configured node groups
        displayName: RTE MCPs from node groups
        path: machineconfigpools
      - description: Conditions represents the latest available observations of MachineConfigPool
          current state.
        displayName: Optional conditions reported for this NodeGroup
        path: machineconfigpools[0].conditions
      - description: NodeGroupConfig represents the latest available configuration
          applied to this MachineConfigPool
        displayName: Optional configuration enforced on this NodeGroup
        path: machineconfigpools[0].config
      version: v1alpha1
    - description: NUMAResourcesScheduler is the Schema for the numaresourcesschedulers
        API
      displayName: NUMA Aware Scheduler
      kind: NUMAResourcesScheduler
      name: numaresourcesschedulers.nodetopology.openshift.io
      resources:
      - kind: Deployment
        name: secondary-scheduler-deployment
        version: v1
      specDescriptors:
      - description: Set the cache resync debug options. Defaults to disable.
        displayName: Scheduler cache resync debug setting
        path: cacheResyncDebug
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Set the cache resync period. Use explicit 0 to disable.
        displayName: Scheduler cache resync period setting
        path: cacheResyncPeriod
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Scheduler container image URL
        displayName: Scheduler container image URL
        path: imageSpec
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Valid values are: "Normal", "Debug", "Trace", "TraceAll". Defaults
          to "Normal".'
        displayName: Scheduler log verbosity
        path: logLevel
      - description: Scheduler name to be used in pod templates
        displayName: Scheduler name
        path: schedulerName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - description: CacheResyncPeriod shows the current cache resync period
        displayName: Scheduler cache resync period
        path: cacheResyncPeriod
      - description: Deployment of the secondary scheduler, namespaced name
        displayName: Scheduler deployment
        path: deployment
      - description: Scheduler name to be used in pod templates
        displayName: Scheduler name
        path: schedulerName
      version: v1
    - description: NUMAResourcesScheduler is the Schema for the numaresourcesschedulers
        API
      displayName: NUMA Aware Scheduler
      kind: NUMAResourcesScheduler
      name: numaresourcesschedulers.nodetopology.openshift.io
      resources:
      - kind: Deployment
        name: secondary-scheduler-deployment
        version: v1
      specDescriptors:
      - description: Set the cache resync period. Use explicit 0 to disable.
        displayName: Scheduler cache resync period setting
        path: cacheResyncPeriod
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Scheduler container image URL
        displayName: Scheduler container image URL
        path: imageSpec
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Valid values are: "Normal", "Debug", "Trace", "TraceAll". Defaults
          to "Normal".'
        displayName: Scheduler log verbosity
        path: logLevel
      - description: Scheduler name to be used in pod templates
        displayName: Scheduler name
        path: schedulerName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - description: Deployment of the secondary scheduler, namespaced name
        displayName: Scheduler deployment
        path: deployment
      - description: Scheduler name to be used in pod templates
        displayName: Scheduler name
        path: schedulerName
      version: v1alpha1
  description: NUMA resources exporter operator
  displayName: numaresources-operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAYNJREFUWIXt1T9rlEEQx/HPnecJGoKJhY+NEgW5VrCxSZpr0oWUKcRgYSoLGwv1RfgWfAnWFlZWKQIRJE00V6XwTxQsdSwygWV5DEeaS/EMLDPP/Gaf/e7swz49hBlaf5aLdwAdQAfQAZwfgLa7OP4TT6tPMw/6TQaPK+EAcxhlXNs3NDngaaUvpx8XuRv4g+clAOzjBRZaFprGPuN1ldtoqXuEXWzWAEdYwvczAiylH6W/iCctdZt4hit4UAJcwDAT984IsYVPGa+26CsY4D3e4MOJ0BA7x99GjIkgesQXYo4YZawaX4nrRJNzFoi9nBvE/fTjrI8ciDvEEXGZGJSU79I/xN+Mf2Gx2s0lzOMnrmbuB+4Wu98u6ufxGxPsZG6A9boDiJtJOskOILYL+n7Gb/O5KbQ14iPxqtj1mNgqaqg6UgMgXqZ4AnArn/fzOIK41gIwzKO5XQEEsVqtMSQOj49MBHpVm+tcfYHUWu+UuO39tT4zOx//gg6gA+gAOoBZ2j82IbSJZWt9tAAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - RTE
  - NUMA
  links:
  - name: Numaresources Operator
    url: https://github.com/openshift-kni/numaresources-operator
  maintainers:
  - email: fromani@redhat.com
    name: fromani
  maturity: stable
  minKubeVersion: 1.23.0
  provider:
    name: Red Hat
  version: 4.14.0
