name: CI E2E - tests not requiring a cluster

on:
  pull_request:
    branches:
      - main
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  e2e-local:
    runs-on: ubuntu-20.04
    env:
      LOG_DIR: /tmp/test_e2e_logs
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Set up golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.6

    - name: Verify modules
      run: go mod verify

    - name: Build test binaries
      run: |
        make binary-e2e-rte

    - name: Build binaries
      run: |
        make binary-rte

    - name: E2E Tests - not requiring a cluster
      run: |
        bin/e2e-nrop-rte.test -ginkgo.focus '.*rte.*local.*'
