apiVersion: v1
kind: ConfigMap
metadata:
  name: topo-aware-scheduler-config
  namespace: placeholder
data:
  "config.yaml": |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: topo-aware-scheduler
        plugins:
          filter:
            disabled:
              - name: '*'
            enabled:
              - name: NodeUnschedulable
              - name: NodeName
              - name: TaintToleration
              - name: NodeAffinity
              - name: NodePorts
              - name: KNIDebug
              - name: NodeResourcesFit
              - name: NodeResourceTopologyMatch
              - name: VolumeRestrictions
              - name: EBSLimits
              - name: GCEPDLimits
              - name: NodeVolumeLimits
              - name: AzureDiskLimits
              - name: VolumeBinding
              - name: VolumeZone
              - name: PodTopologySpread
              - name: InterPodAffinity
          reserve:
            enabled:
              - name: NodeResourceTopologyMatch
          score:
            enabled:
              - name: NodeResourceTopologyMatch
        # optional plugin configs
        pluginConfig:
        - name: NodeResourceTopologyMatch
          args:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: NodeResourceTopologyMatchArgs
            scoringStrategy:
              type: LeastAllocated
